site_name: NearIT Android
theme: readthedocs
extra_css : ["css/nearitdocs.css"]
pages:
  - 'Getting started' : 'index.md'
  - 'User Guide' :
    - 'Installation' : 'installation.md'
    - 'Enable Triggers' : 'enable-triggers.md'
    - 'Handle Recipe Content' : 'handle-content.md'
    - 'User Profiling' : 'user-profilation.md'
  - 'Advanced Topics' :
    - 'Custom Background Notification' : 'custom-bkg-notification.md'
    - 'Testing' : 'testing.md'
  - 'Samples' :
    - 'Integration Samples' : 'integration-samples.md'
    - 'Best Practice on Permissions Request' : 'permission-request-sample.md'
  - 'Other resources' :
    - 'Logging' : 'logging.md'
    - 'Firebase Help' : 'firebase.md'
