site_name: NearIT Android
theme: readthedocs
extra_css : ["css/nearitdocs.css"]
pages:
  - 'Getting started' : 'index.md'
  - 'User Guide' :
    - 'Installation' : 'installation.md'
    - 'Enable Triggers' : 'enable-triggers.md'
    - 'Handle recipe content' : 'handle-content.md'
    - 'User profiling' : 'user-profilation.md'
  - 'Advanced topics' :
    - 'Custom background notification' : 'custom-bkg-notification.md'
    - 'Testing' : 'testing.md'
  - 'Samples' :
    - 'Integration samples' : 'integration-samples.md'
    - 'Best practice on permissions request' : 'permission-request-sample.md'
  - 'Other resources' :
    - 'Pro-guard & logging' : 'proguard.md'
    - 'Firebase help' : 'firebase.md'
